- link:
    ~/.config/safeeyes/style/safeeyes_style.css:
      force: true
      path: safeeyes/safeeyes_style.css
    ~/.config/safeeyes/safeeyes.json:
      force: true
      path: safeeyes/safeeyes.json
