- link:
    ~/.vimrc: vim/vimrc
    ~/.vim/coc-settings.json: vim/coc-settings.json
    ~/.vim/cocnvim.vim: vim/cocnvim.vim

- clean: [
    '~/.vim'
]

- shell:
  - [vim -c 'PlugInstall' +qall, Installing vim plugins]
