# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

zstyle :prompt:shrink_path fish yes

# Use antigen
source $HOME/.antigen.zsh

POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir
  vcs
  newline
  status
  virtualenv
)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MODE='nerdfont-complete'

[[ -f ~/.zsh/zsh_zstyle ]] && source ~/.zsh/zsh_zstyle

# Use Oh-My-Zsh
antigen use oh-my-zsh

# Set theme
antigen theme romkatv/powerlevel10k

# Set plugins (plugins not part of Oh-My-Zsh can be installed using githubusername/repo)
antigen bundle git
antigen bundle tig
antigen bundle archlinux
antigen bundle systemd
antigen bundle extract
antigen bundle fasd
antigen bundle fzf
antigen bundle ssh-agent
antigen bundle web-search
antigen bundle colored-man-pages
antigen bundle shrink-path
antigen bundle wfxr/forgit

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

# Keep at the end
antigen bundle zsh-users/zsh-syntax-highlighting

# Apply changes
antigen apply

[[ -f ~/.zsh/zsh_functions ]] && source ~/.zsh/zsh_functions
[[ -f ~/.zsh/zsh_local ]] && source ~/.zsh/zsh_local
[[ -f ~/.zsh/zsh_private ]] && source ~/.zsh/zsh_private

# Source fzf-extras (need to download it manually from PR, conflicts with fasd?)
[[ -f ~/.zsh/fzf-extras.zsh ]] && source ~/.zsh/fzf-extras.zsh

# Required by athame
# unset zle_bracketed_paste

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


export EDITOR=vim
